# node as base image
FROM node:18-alpine

# Working directory
WORKDIR /app

# Copy package.json 
COPY package*.json ./

# Install dependencies
RUN npm install --production


COPY . .

# Expose backend port
EXPOSE 3000

# Start the application
CMD ["node", "index.js"]
