pipeline{
    agent any

    environment {
    AWS_REGION     = "us-east-1"
    AWS_ACCOUNT_ID = "145678291359"

    BACKEND_REPO   = "backend-repo"
    FRONTEND_REPO  = "frontend-repo"

    ECS_CLUSTER    = "Proz_ECS_Cluster"

    BACKEND_SERVICE  = "backend_service"
    FRONTEND_SERVICE = "frontend-service"

    BACKEND_TASK_FAMILY = "backend-task"
    FRONTEND_TASK_FAMILY = "frontend-task"
}

    stages{
        stage('Checkout'){
            steps{
                checkout scm
            }
        }

        stage('SonarQube Analysis'){
            steps{
               script{
                    def scannerHome = tool 'SonarScanner'

                    withSonarQubeEnv('SonarQube') {
                        sh """
                        ${scannerHome}/bin/sonar-scanner \
                        -Dsonar.projectKey=Employee-Management-System \
                        -Dsonar.projectName="Employee Management System" \
                        -Dsonar.projectVersion=1.0 \
                        -Dsonar.sources=Proz/Employee_Management/Server,Proz/Employee_Management/Client/src \
                        -Dsonar.exclusions=**/node_modules/**,**/dist/** \
                        -Dsonar.sourceEncoding=UTF-8
                        """
                    }
               }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Build-Frontend-Docker-File'){
            steps{
                dir('Proz/Employee_Management/Client') {

                    withCredentials([
                        string(credentialsId: 'VITE_BACKEND_URL',
                            variable: 'BACKEND_URL')
                    ]) {

                        sh """
                        docker build \
                        --build-arg VITE_BACKEND_URL=$BACKEND_URL \
                        -t frontend:${BUILD_NUMBER} .
                        """
                    }
                }
            }
        }

        stage('Build-Backend-DockerFile'){
            steps{
                dir('Proz/Employee_Management/Server'){
                    sh 'docker build -t backend:${BUILD_NUMBER} .'
                }
            }
        }

        stage('Trivy Image Scan') {
            steps {
                sh '''
                mkdir -p trivy-reports

                echo "=============================="
                echo "Scanning Backend Image"
                echo "=============================="

                trivy image \
                --severity HIGH,CRITICAL \
                --ignore-unfixed \
                --format table \
                --output trivy-reports/backend-report.txt \
                --exit-code 0 \
                backend:${BUILD_NUMBER}

                echo "=============================="
                echo "Scanning Frontend Image"
                echo "=============================="

                trivy image \
                --severity HIGH,CRITICAL \
                --ignore-unfixed \
                --format table \
                --output trivy-reports/frontend-report.txt \
                --exit-code 0 \
                frontend:${BUILD_NUMBER}
                '''
            }
        }
        stage('Login to Amazon ECR') {
            steps {
                sh '''

                aws ecr get-login-password --region ${AWS_REGION} | \
                docker login \
                --username AWS \
                --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
                '''
            }
        
        }
        stage('Tag Docker Image') {
            steps {
                sh '''
                docker tag backend:${BUILD_NUMBER} \
                ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${BACKEND_REPO}:${BUILD_NUMBER}

                docker tag backend:${BUILD_NUMBER} \
                ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${BACKEND_REPO}:latest

                docker tag frontend:${BUILD_NUMBER} \
                ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${FRONTEND_REPO}:${BUILD_NUMBER}

                docker tag frontend:${BUILD_NUMBER} \
                ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${FRONTEND_REPO}:latest
                '''
            }
        }

        stage('Push Docker Image to Amazon ECR') {
            steps {
                sh '''
                docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${BACKEND_REPO}:${BUILD_NUMBER}
                docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${BACKEND_REPO}:latest

                docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${FRONTEND_REPO}:${BUILD_NUMBER}
                docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${FRONTEND_REPO}:latest
                '''
            }
        }
        stage('Create Backend Task Definition Revision') {
            steps {
                sh '''
                aws ecs describe-task-definition \
                    --task-definition ${BACKEND_TASK_FAMILY} \
                    --region ${AWS_REGION} \
                    --query taskDefinition > backend-task.json

                jq 'del(
                    .taskDefinitionArn,
                    .revision,
                    .status,
                    .requiresAttributes,
                    .compatibilities,
                    .registeredAt,
                    .registeredBy
                )' backend-task.json > backend-task-clean.json

                jq --arg IMAGE "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${BACKEND_REPO}:${BUILD_NUMBER}" \
                '.containerDefinitions[0].image = $IMAGE' \
                backend-task-clean.json > backend-task-new.json

                aws ecs register-task-definition \
                    --cli-input-json file://backend-task-new.json \
                    --region ${AWS_REGION}
                '''
            }
        }
        stage('Deploy Backend') {
            steps {
                sh '''
                aws ecs update-service \
                    --cluster ${ECS_CLUSTER} \
                    --service ${BACKEND_SERVICE} \
                    --task-definition ${BACKEND_TASK_FAMILY} \
                    --region ${AWS_REGION}
                '''
            }
        }
        stage('Wait for Backend Deployment') {
            steps {
                sh '''
                aws ecs wait services-stable \
                    --cluster ${ECS_CLUSTER} \
                    --services ${BACKEND_SERVICE} \
                    --region ${AWS_REGION}
                '''
            }
        }

        stage('Create Frontend Task Definition Revision') {
            steps {
                sh '''
                aws ecs describe-task-definition \
                    --task-definition ${FRONTEND_TASK_FAMILY} \
                    --region ${AWS_REGION} \
                    --query taskDefinition > frontend-task.json

                jq 'del(
                    .taskDefinitionArn,
                    .revision,
                    .status,
                    .requiresAttributes,
                    .compatibilities,
                    .registeredAt,
                    .registeredBy
                )' frontend-task.json > frontend-task-clean.json

                jq --arg IMAGE "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${FRONTEND_REPO}:${BUILD_NUMBER}" \
                '.containerDefinitions[0].image = $IMAGE' \
                frontend-task-clean.json > frontend-task-new.json

                aws ecs register-task-definition \
                    --cli-input-json file://frontend-task-new.json \
                    --region ${AWS_REGION}
                '''
            }
        }

        stage('Deploy Frontend') {
            steps {
                sh '''
                aws ecs update-service \
                    --cluster ${ECS_CLUSTER} \
                    --service ${FRONTEND_SERVICE} \
                    --task-definition ${FRONTEND_TASK_FAMILY} \
                    --region ${AWS_REGION}
                '''
            }
        }

        stage('Wait for Frontend Deployment') {
            steps {
                sh '''
                aws ecs wait services-stable \
                    --cluster ${ECS_CLUSTER} \
                    --services ${FRONTEND_SERVICE} \
                    --region ${AWS_REGION}
                '''
            }
        }
        
    }
    post {
        always {
            archiveArtifacts artifacts: 'trivy-reports/*.txt', fingerprint: true
        }
    }
}