pipeline{
    agent any

    stages{
        stage('Checkout'){
            steps{
                checkout scm
            }
        }

        stage('Frontend-Install Dependencies'){
            agent{
                docker {
                    image 'node:18-alpine'
                    reuseNode true
                }
            }
            steps{
                dir('Proz/Employee_Management/Client'){
                    sh '''
                        export HOME=$PWD
                        export npm_config_cache=$PWD/.npm

                        npm ci
                       
                    '''
                }
            }
        }

        stage('Frontend-Build'){
            agent{
                docker {
                    image 'node:18-alpine'
                    reuseNode true
                }
            }
            steps{
                dir('Proz/Employee_Management/Client'){
                    sh 'npm run build'
                }
            }
        }

    
        
        stage('Backend-Install Dependencies'){
            agent{
                docker{
                    image 'node:18-alpine'
                    reuseNode true
                }
            }
            steps{
                dir('Proz/Employee_Management/Server'){
                    sh '''
                        export HOME=$PWD
                        export npm_config_cache=$PWD/.npm

                        npm install
                    '''
                }
            }
        }
        
     }
}